Fix validation error with UniversalFederationPlugin
```
ValidationError: Invalid options object. Module Federation Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'isServer'.
```
Above error was thrown when passing `isServer` to the plugin due to the whole options object got passed further Module Federation Plugin & `isServer` was not a valid option. Just need to extract it out & pass through the rest.